# Generated by Django 4.1.1 on 2022-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EjemploORM', '0005_alter_productos_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.IntegerField(max_length=11)),
                ('name_prod', models.CharField(max_length=100)),
                ('price_prod', models.IntegerField(max_length=10)),
                ('inserted', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
    ]
