# Generated by Django 4.1.1 on 2022-12-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EjemploORM', '0006_log_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormCategoria',
            fields=[
                ('id_categoria', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ejemploorm_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormCiudad',
            fields=[
                ('id_ciudad', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejemploorm_ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormCliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('fecha_registro', models.DateTimeField()),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejemploorm_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormComuna',
            fields=[
                ('id_comuna', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejemploorm_comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormCredencial',
            fields=[
                ('id_credencial', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_update', models.DateField()),
            ],
            options={
                'db_table': 'ejemploorm_credencial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormHistorial',
            fields=[
                ('id_historial', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ejemploorm_historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormImgproducto',
            fields=[
                ('id_img', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ejemploorm_imgproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormLogProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prod', models.IntegerField()),
                ('name_prod', models.CharField(max_length=100)),
                ('price_prod', models.IntegerField()),
                ('inserted', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejemploorm_log_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormOrdencompra',
            fields=[
                ('nro_orden', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('precio', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('medio_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ejemploorm_ordencompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormPais',
            fields=[
                ('id_pais', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejemploorm_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormPersona',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=40, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('contrasenna', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('perfil', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'ejemploorm_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormProducto',
            fields=[
                ('id_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio_cl', models.PositiveIntegerField()),
                ('precio_usd', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('introduccion', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=30)),
                ('materiales', models.CharField(max_length=100)),
                ('medidas', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('archivo_pdf', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ejemploorm_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('content_file', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ejemploorm_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormProductoscomprados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('date_purchased', models.DateTimeField()),
            ],
            options={
                'db_table': 'ejemploorm_productoscomprados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormRegion',
            fields=[
                ('id_region', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejemploorm_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormRol',
            fields=[
                ('id_rol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rol_admin', models.IntegerField()),
                ('rol_cliente', models.IntegerField()),
                ('rol_emprendedor', models.IntegerField()),
            ],
            options={
                'db_table': 'ejemploorm_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EjemploormVenta',
            fields=[
                ('id_venta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
            ],
            options={
                'db_table': 'ejemploorm_venta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='log_productos',
        ),
        migrations.AlterField(
            model_name='productoscomprados',
            name='Productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EjemploORM.ejemploormproductos'),
        ),
        migrations.AlterField(
            model_name='productoscomprados',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='EjemploORM.ejemploormpersona'),
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
